<?php
// commands
define('GET_SMS_CODE', 0);
define('CONFIRM_SMS_CODE', 1);
define('CREATE_SHIPPING_ADDRESS', 2);

// status constants
define('SEND_SMS_CODE_SUCCESS', 1);
define('SEND_SMS_CODE_FAILURE', 0);
define('CONFIRM_SMS_CODE_SUCCESS', 1);
define('CONFIRM_SMS_CODE_FAILURE', 0);
define('SHIPPING_ADDRESS_CHECK_SUCCESS', 1);
define('SHIPPING_ADDRESS_CHECK_FAILURE', 0);

// Coupon constans
define('COUPON_DISCOUNT_METHOD_PERCENTAGE', 1);
define('COUPON_DISCOUNT_METHOD_VALUE', 2);